---
language: python
matrix:
  include:
    - python: 2.7
      env: ANSIBLE_VERSION=2.5
    - python: 2.7
      env: ANSIBLE_VERSION=2.6
    - python: 2.7
      env: ANSIBLE_VERSION=2.7
    - python: 3.5
      env: ANSIBLE_VERSION=2.5
    - python: 3.5
      env: ANSIBLE_VERSION=2.6
    - python: 3.5
      env: ANSIBLE_VERSION=2.7
    - python: 3.6
      env: ANSIBLE_VERSION=2.5
    - python: 3.6
      env: ANSIBLE_VERSION=2.6
    - python: 3.6
      env: ANSIBLE_VERSION=2.7

install:
  - python -m pip install ansible==$ANSIBLE_VERSION

script:
  - ansible-playbook tests/test.yml -i tests/inventory -vvv